services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: diet_backend
    restart: always
    # 不需要暴露 ports，因為它只在 Docker 內部網路與前端溝通

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: diet_frontend
    ports:
      - "8080:80" # 將遠端主機的 8080 對應到 Nginx 的 80
    depends_on:
      - backend
    restart: always
