FROM rust:latest

RUN apt-get update && apt-get install -y \
    build-essential \
    cmake \
    perl \
    nasm \
    libclang-dev \
    pkg-config \
    libssl-dev \
    curl \
    && rm -rf /var/lib/apt/lists/*

RUN curl -L --proto '=https' --tlsv1.2 -sSf https://raw.githubusercontent.com/cargo-bins/cargo-binstall/main/install-from-binstall-release.sh | bash


RUN cargo binstall cargo-watch -y

WORKDIR /app

ENV LIBCLANG_PATH=/usr/lib/llvm-11/lib

CMD ["cargo", "watch","--poll", "-x", "run"]